src/Entity/Freelance.php
<?php

namespace App\Entity;

use App\Repository\FreelanceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FreelanceRepository::class)]
class Freelance
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\OneToOne(mappedBy: 'freelance', cascade: ['persist', 'remove'])]
    private ?User $user = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 10)]
    private ?string $zip_code = null;

    #[ORM\Column(length: 255)]
    private ?string $country = null;

    #[ORM\Column(length: 9)]
    private ?string $siren = null;

    #[ORM\Column(length: 14)]
    private ?string $siret = null;

    #[ORM\Column(length: 14, nullable: true)]
    private ?string $duns_number = null;

    #[ORM\Column(length: 100)]
    private ?string $status = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getZipCode(): ?string
    {
        return $this->zip_code;
    }

    public function setZipCode(string $zip_code): self
    {
        $this->zip_code = $zip_code;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getSiren(): ?string
    {
        return $this->siren;
    }

    public function setSiren(string $siren): self
    {
        $this->siren = $siren;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getDunsNumber(): ?string
    {
        return $this->duns_number;
    }

    public function setDunsNumber(string $duns_number): self
    {
        $this->duns_number = $duns_number;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        // unset the owning side of the relation if necessary
        if ($user === null && $this->user !== null) {
            $this->user->setFreelance(null);
        }

        // set the owning side of the relation if necessary
        if ($user !== null && $user->getFreelance() !== $this) {
            $user->setFreelance($this);
        }

        $this->user = $user;

        return $this;
    }
}

src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
class Invoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'invoices')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'invoices')]
    private ?Company $company = null;

    #[ORM\Column(length: 255)]
    private ?string $filename = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column]
    private ?bool $applyTVA = null;

    #[ORM\Column(nullable: true)]
    private ?float $tva = 0;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $invoiceDate = null;

    #[ORM\OneToMany(mappedBy: 'invoice', targetEntity: InvoiceDetail::class)]
    private Collection $invoiceDetails;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    public function __construct()
    {
        $this->invoiceDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function isApplyTVA(): ?bool
    {
        return $this->applyTVA;
    }

    public function setApplyTVA(bool $applyTVA): static
    {
        $this->applyTVA = $applyTVA;

        return $this;
    }

    public function getTva(): ?float
    {
        return $this->tva;
    }

    public function setTva(?float $tva): static
    {
        $this->tva = $tva;

        return $this;
    }

    public function getInvoiceDate(): ?\DateTimeInterface
    {
        return $this->invoiceDate;
    }

    public function setInvoiceDate(\DateTimeInterface $invoiceDate): self
    {
        $this->invoiceDate = $invoiceDate;

        return $this;
    }

    /**
     * @return Collection<int, InvoiceDetail>
     */
    public function getInvoiceDetails(): Collection
    {
        return $this->invoiceDetails;
    }

    public function addInvoiceDetail(InvoiceDetail $invoiceDetail): self
    {
        if (!$this->invoiceDetails->contains($invoiceDetail)) {
            $this->invoiceDetails->add($invoiceDetail);
            $invoiceDetail->setInvoice($this);
        }

        return $this;
    }

    public function removeInvoiceDetail(InvoiceDetail $invoiceDetail): self
    {
        if ($this->invoiceDetails->removeElement($invoiceDetail)) {
            // set the owning side to null (unless already changed)
            if ($invoiceDetail->getInvoice() === $this) {
                $invoiceDetail->setInvoice(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getAmount() : float {
        $amount = 0;

        foreach($this->invoiceDetails as $invoiceDetail) {
            $amount += $invoiceDetail->getPrice();
        }

        return $amount;
    }

    public function getTvaAmount() : float {
        $amount = 0;

        if($this->applyTVA) {
            foreach($this->invoiceDetails as $invoiceDetail) {
                $amount += $invoiceDetail->getPrice() * ($this->tva / 100);
            }
        }

        return $amount;
    }

    public function getTotalAmount() : float {
        $amount = 0;

        foreach($this->invoiceDetails as $invoiceDetail) {
            $amount += $invoiceDetail->getPrice();
            if($this->applyTVA) {
                $amount += $invoiceDetail->getPrice() * ($this->tva / 100);
            }
        }

        return $amount;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $firstname = null;

    #[ORM\Column(length: 255)]
    private ?string $lastname = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $birthDate = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?Freelance $freelance = null;

    #[ORM\ManyToMany(targetEntity: Company::class, inversedBy: 'users')]
    private Collection $companies;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Invoice::class)]
    private Collection $invoices;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Estimate::class)]
    private Collection $estimates;

    public function __construct()
    {
        $this->companies = new ArrayCollection();
        $this->invoices = new ArrayCollection();
        $this->estimates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFullname(): ?string
    {
        return $this->firstname . " " . $this->lastname;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(\DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function isAdmin(): bool {
        $isAdmin = false;

        if(in_array("ROLE_ADMIN", $this->getRoles())) {
            $isAdmin = true;
        }

        return $isAdmin;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getFreelance(): ?Freelance
    {
        return $this->freelance;
    }

    public function setFreelance(?Freelance $freelance): self
    {
        $this->freelance = $freelance;

        return $this;
    }

    /**
     * @return Collection<int, Company>
     */
    public function getCompanies(): Collection
    {
        return $this->companies;
    }

    /**
     * Find a company by the id
     * 
     * @param int company id
     * @return Company|null
     */
    public function getCompany(int $companyID) : Company|null {        
        foreach($this->companies as $company) {
            if($company->getId() === $companyID) {
                return $company;
            }
        }

        return null;
    }

    /**
     * Find a company using the same siret in the list of the user
     * 
     * @param string siret
     * @return Company|null
     */
    public function findCompanyBySiret(string $siret) : Company {
        foreach($this->companies as $company) {
            if($company->getSiret() == $siret) {
                return $company;
            }
        }

        return null;
    }

    public function countCompanies() : int {
        return count($this->companies);
    }

    public function addCompany(Company $company): self
    {
        if (!$this->companies->contains($company)) {
            $this->companies->add($company);
        }

        return $this;
    }

    public function removeCompany(Company $company): self
    {
        $this->companies->removeElement($company);

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setUser($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getUser() === $this) {
                $invoice->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Estimate>
     */
    public function getEstimates(): Collection
    {
        return $this->estimates;
    }

    public function addEstimate(Estimate $estimate): self
    {
        if (!$this->estimates->contains($estimate)) {
            $this->estimates->add($estimate);
            $estimate->setUser($this);
        }

        return $this;
    }

    public function removeEstimate(Estimate $estimate): self
    {
        if ($this->estimates->removeElement($estimate)) {
            // set the owning side to null (unless already changed)
            if ($estimate->getUser() === $this) {
                $estimate->setUser(null);
            }
        }

        return $this;
    }
}

templates/models/estimate.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <title>{{ estimate.label }}</title>
        <style>
            html, body, .page {
                font-size: .9rem;
                background-color: #ffffff;
                -moz-osx-font-smoothing: grayscale;
                -webkit-font-smoothing: antialiased;
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue', sans-serif;
            }

            /* File PDF */
            .file-pdf {
                display: flex;
                font-size: 1rem;
                margin-top: 40px;
                flex-direction: column;
            }

                .file-pdf > .pdf-header {
                    top: -40px;
                    left: 0px;
                    right: 0px;
                    height: 50px;
                    position: fixed;
                    text-align: center;
                    line-height: 35px;
                }

                .file-pdf > .pdf-content {
                    margin-top: 25px;
                }

                .file-pdf > .pdf-footer {
                    position: fixed; 
                    bottom: -60px; 
                    left: 0px; 
                    right: 0px;
                    height: 50px; 

                    /** Extra personal styles **/
                    background-color: #03a9f4;
                    color: white;
                    text-align: center;
                    line-height: 35px;
                }

                    .file-pdf > .pdf-footer > p {
                        margin: 0;
                        padding: 0;
                    }
            
            /* Table */
            .table {
                margin: 0;
                padding: 0;
                width: 100%;
                overflow: hidden;
                position: relative;
                border-collapse: collapse;
                background-color: #ffffff;
                border-radius: 5px 5px 0 0;
            }
                .table > thead {
                    color: #ffffff;
                    background-color: #2962ff;
                }

                .table > thead > tr > th {
                    padding: 10px;
                }

                .table > tbody > tr:nth-child(even) {
                    background-color: #f2f2f2;
                }
                
                .table > tbody > tr:hover {
                    background-color: #c8c8c8;
                }

                .table > tbody > tr > td {
                    padding: 10px;
                }

            /* Service provider */
            .service-provider {
                top: 0;
            }

                .service-provider > .-identity {
                    gap: 5px;
                    display: flex;
                    flex-direction: column;
                }

                .service-provider > .-address {
                    margin: 5px 0;
                }

                .service-provider > .-contact {
                    gap: 5px;
                    display: flex;
                    flex-direction: column;
                }

            /* Common */
            .d-flex {
                display: flex;
            }

            .txt-center {
                text-align: center;
            }

            .txt-left {
                text-align: left;
            }

            .txt-right {
                text-align: right;
            }

            .txt-bold {
                font-weight: 700;
            }

            .f-right {
                float: right;
            }

            .w-50 {
                width: 50%;
            }

            .w-100 {
                width: 100%;
            }

            .m-0 {
                margin: 0;
            }

            .p-0 {
                margin: 0;
            }

            .mt-25px {
                margin-top: 25px;
            }
            
            .mt-50px {
                margin-top: 50px;
            }
        </style>
    </head>
    <body>
        <div class="page">
            <div class="file-pdf">
                <div class="pdf-header">
                    <h2>Estimate</h2>
                </div>
                <div class="pdf-content">
                    <div class="m-0 p-0">
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td class="w-50">
                                        <h3 class="txt-bold txt-left">Prestataire</h3>
                                        <div class="service-provider txt-left">
                                            <div class="-identity">
                                                <span>{{ user.fullname }}</span>
                                            </div>
                                            <div class="-address">
                                                {% if user.freelance is not same as (null) %}
                                                    <span>{{ user.freelance.address ~ ", " ~ user.freelance.zipCode ~ " " ~ user.freelance.city ~ ", " ~ user.freelance.country }}</span>
                                                {% endif %}
                                            </div>
                                            <div class="-contact">
                                                <span>{{ user.email }}</span>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="w-50">
                                        <h3 class="txt-bold txt-right">Client</h3>
                                        <div class="service-provider txt-right">
                                            <div class="-identity">
                                                <span>{{ company.name }}</span>
                                            </div>
                                            <div class="-address">
                                                <span>{{ company.address ~ ", " ~ company.city ~ " " ~ company.zipCode ~ ", " ~ company.country  }}</span>
                                            </div>
                                            <div class="-contact">
                                                {% if company.phone is defined %}<span>{{ company.phone }}</span>{% endif %}
                                                {% if company.email is defined %}<span>{{ company.email }}</span>{% endif %}
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-50px">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Description</th>
                                    <th>Quantity</th>
                                    <th>Nbr days</th>
                                    <th>Unit. Price</th>
                                    <th>Amount HT</th>
                                    <th>Amount TTC</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for estimateDetail in estimate.estimateDetails %}
                                    <tr>
                                        <td>{{ estimateDetail.label }}</td>
                                        <td class="txt-center">{{ estimateDetail.quantity }}</td>
                                        <td class="txt-center">{{ estimateDetail.nbrDays }}</td>
                                        <td class="txt-center">{{ estimateDetail.price }}</td>
                                        <td class="txt-center">{{ (estimateDetail.price * estimateDetail.nbrDays) * estimateDetail.quantity }}</td>
                                        <td class="txt-center">{{ estimateDetail.totalAmount }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-25px">
                        <table class="w-100">
                            <tbody>
                                <tr>
                                    <td class="w-50"></td>
                                    <td class="w-50">
                                        <table class="table">
                                            <tbody>
                                                <tr>
                                                    <td>Amount</td>
                                                    <td class="txt-center">{{ estimate.amount() }}</td>
                                                </tr>
                                                <tr>
                                                    <td>TVA</td>
                                                    <td class="txt-center">{{ estimate.tvaAmount() }}</td>
                                                </tr>
                                                <tr>
                                                    <td class="txt-bold">Total amount</td>
                                                    <td class="txt-center">{{ estimate.totalAmount() }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>